version: '3.3'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'yii_tokens'
      POSTGRES_USER: 'yii_tokens'
      POSTGRES_PASSWORD: 'demo'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5492:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data/pgdata
volumes:
  my-db:
